"""0001

Revision ID: 7571f970f088
Revises: 
Create Date: 2022-11-02 08:40:00.963715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7571f970f088'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('auth_merchant_id', sa.Integer(), nullable=False),
    sa.Column('auth_store_id', sa.Integer(), nullable=False),
    sa.Column('cart_master_id', sa.Integer(), nullable=False),
    sa.Column('api_url', sa.String(length=255), nullable=False),
    sa.Column('api_version', sa.String(length=255), nullable=False),
    sa.Column('api_auth_details', sa.JSON(), nullable=False),
    sa.Column('cart_type', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cart_domain', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_store_id')
    )
    op.create_table('plans',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_store_id'), 'plans', ['store_id'], unique=True)
    op.create_table('portal_settings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('current_domain', sa.String(length=512), nullable=False),
    sa.Column('brand_logo', sa.String(length=1024), nullable=False),
    sa.Column('favicon', sa.String(length=1024), nullable=False),
    sa.Column('main_title', sa.String(length=128), nullable=False),
    sa.Column('btn_txt', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_settings_current_domain'), 'portal_settings', ['current_domain'], unique=True)
    op.create_index(op.f('ix_portal_settings_store_id'), 'portal_settings', ['store_id'], unique=True)
    op.create_table('purchase_reason_settings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'name', name='unique_idx_store_id_name')
    )
    op.create_index(op.f('ix_purchase_reason_settings_store_id'), 'purchase_reason_settings', ['store_id'], unique=False)
    op.create_index('store_name_idx', 'purchase_reason_settings', ['store_id', 'name'], unique=False)
    op.create_table('return_address_settings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=128), nullable=False),
    sa.Column('postal_code', sa.String(length=128), nullable=False),
    sa.Column('prefectures', sa.String(length=255), nullable=False),
    sa.Column('return_street', sa.String(length=255), nullable=False),
    sa.Column('return_room', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_address_settings_store_id'), 'return_address_settings', ['store_id'], unique=False)
    op.create_table('return_reason_settings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'name', name='unique_idx_store_id_name')
    )
    op.create_index(op.f('ix_return_reason_settings_store_id'), 'return_reason_settings', ['store_id'], unique=False)
    op.create_index('store_name_idx', 'return_reason_settings', ['store_id', 'name'], unique=False)
    op.create_table('sender_notification_settings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sender_name', sa.String(length=128), nullable=False),
    sa.Column('mail_address', sa.String(length=255), nullable=False),
    sa.Column('verify', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sender_notification_settings_store_id'), 'sender_notification_settings', ['store_id'], unique=True)
    op.create_table('try_order_groups',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('cart_order_id', sa.Integer(), nullable=False),
    sa.Column('cart_order_gid', sa.String(length=255), nullable=True),
    sa.Column('cart_order_number', sa.String(length=255), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('purchase_status', sa.String(length=128), nullable=False),
    sa.Column('return_status', sa.String(length=128), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('shipment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'request_id', name='unique_idx_store_id_request')
    )
    op.create_index(op.f('ix_try_order_groups_cart_order_id'), 'try_order_groups', ['cart_order_id'], unique=False)
    op.create_index(op.f('ix_try_order_groups_cart_order_number'), 'try_order_groups', ['cart_order_number'], unique=False)
    op.create_index(op.f('ix_try_order_groups_request_id'), 'try_order_groups', ['request_id'], unique=False)
    op.create_index(op.f('ix_try_order_groups_store_id'), 'try_order_groups', ['store_id'], unique=False)
    op.create_index('store_order_idx', 'try_order_groups', ['store_id', 'cart_order_id'], unique=False)
    op.create_index('store_request_idx', 'try_order_groups', ['store_id', 'request_id'], unique=False)
    op.create_table('try_order_settings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('id_active', sa.Boolean(), nullable=False),
    sa.Column('try_flag', sa.String(length=255), nullable=False),
    sa.Column('selling_plan_group_id', sa.Integer(), nullable=False),
    sa.Column('try_deadline', sa.Integer(), nullable=False),
    sa.Column('return_deadline', sa.Integer(), nullable=False),
    sa.Column('payment_deadline', sa.Integer(), nullable=False),
    sa.Column('item_limit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_try_order_settings_selling_plan_group_id'), 'try_order_settings', ['selling_plan_group_id'], unique=False)
    op.create_index(op.f('ix_try_order_settings_store_id'), 'try_order_settings', ['store_id'], unique=False)
    op.create_index('store_selling_plan_idx', 'try_order_settings', ['store_id', 'selling_plan_group_id'], unique=False)
    op.create_table('mail_templates',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sender_delivery_notification_setting', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=False),
    sa.Column('html_subject_template', sa.String(length=255), nullable=False),
    sa.Column('mobile_subject_template', sa.String(length=255), nullable=False),
    sa.Column('html_content_template', sa.Text(), nullable=False),
    sa.Column('html_json_content_template', sa.JSON(), nullable=False),
    sa.Column('mobile_content_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sender_delivery_notification_setting'], ['sender_notification_settings.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'status', name='unique_idx_store_id_status')
    )
    op.create_index(op.f('ix_mail_templates_sender_delivery_notification_setting'), 'mail_templates', ['sender_delivery_notification_setting'], unique=False)
    op.create_index(op.f('ix_mail_templates_store_id'), 'mail_templates', ['store_id'], unique=False)
    op.create_table('reatures',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reatures_plan_id'), 'reatures', ['plan_id'], unique=False)
    op.create_table('sms_templates',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sender_delivery_notification_setting', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=False),
    sa.Column('sms_content_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sender_delivery_notification_setting'], ['sender_notification_settings.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'status', name='unique_idx_store_id_status')
    )
    op.create_index(op.f('ix_sms_templates_sender_delivery_notification_setting'), 'sms_templates', ['sender_delivery_notification_setting'], unique=False)
    op.create_index(op.f('ix_sms_templates_store_id'), 'sms_templates', ['store_id'], unique=False)
    op.create_table('try_labels',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['order_group_id'], ['try_order_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_try_labels_name'), 'try_labels', ['name'], unique=False)
    op.create_table('try_orders',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('order_group_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_gid', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('item_img', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('discount_code', sa.String(length=512), nullable=True),
    sa.Column('is_purchase', sa.Boolean(), nullable=False),
    sa.Column('is_return', sa.Boolean(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('is_resaleable', sa.Boolean(), nullable=True),
    sa.Column('memo', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['order_group_id'], ['try_order_groups.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_try_orders_item_id'), 'try_orders', ['item_id'], unique=False)
    op.create_index(op.f('ix_try_orders_store_id'), 'try_orders', ['store_id'], unique=False)
    op.create_index('store_item_idx', 'try_orders', ['store_id', 'item_id'], unique=False)
    op.create_index('store_sku_idx', 'try_orders', ['store_id', 'sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('store_sku_idx', table_name='try_orders')
    op.drop_index('store_item_idx', table_name='try_orders')
    op.drop_index(op.f('ix_try_orders_store_id'), table_name='try_orders')
    op.drop_index(op.f('ix_try_orders_item_id'), table_name='try_orders')
    op.drop_table('try_orders')
    op.drop_index(op.f('ix_try_labels_name'), table_name='try_labels')
    op.drop_table('try_labels')
    op.drop_index(op.f('ix_sms_templates_store_id'), table_name='sms_templates')
    op.drop_index(op.f('ix_sms_templates_sender_delivery_notification_setting'), table_name='sms_templates')
    op.drop_table('sms_templates')
    op.drop_index(op.f('ix_reatures_plan_id'), table_name='reatures')
    op.drop_table('reatures')
    op.drop_index(op.f('ix_mail_templates_store_id'), table_name='mail_templates')
    op.drop_index(op.f('ix_mail_templates_sender_delivery_notification_setting'), table_name='mail_templates')
    op.drop_table('mail_templates')
    op.drop_index('store_selling_plan_idx', table_name='try_order_settings')
    op.drop_index(op.f('ix_try_order_settings_store_id'), table_name='try_order_settings')
    op.drop_index(op.f('ix_try_order_settings_selling_plan_group_id'), table_name='try_order_settings')
    op.drop_table('try_order_settings')
    op.drop_index('store_request_idx', table_name='try_order_groups')
    op.drop_index('store_order_idx', table_name='try_order_groups')
    op.drop_index(op.f('ix_try_order_groups_store_id'), table_name='try_order_groups')
    op.drop_index(op.f('ix_try_order_groups_request_id'), table_name='try_order_groups')
    op.drop_index(op.f('ix_try_order_groups_cart_order_number'), table_name='try_order_groups')
    op.drop_index(op.f('ix_try_order_groups_cart_order_id'), table_name='try_order_groups')
    op.drop_table('try_order_groups')
    op.drop_index(op.f('ix_sender_notification_settings_store_id'), table_name='sender_notification_settings')
    op.drop_table('sender_notification_settings')
    op.drop_index('store_name_idx', table_name='return_reason_settings')
    op.drop_index(op.f('ix_return_reason_settings_store_id'), table_name='return_reason_settings')
    op.drop_table('return_reason_settings')
    op.drop_index(op.f('ix_return_address_settings_store_id'), table_name='return_address_settings')
    op.drop_table('return_address_settings')
    op.drop_index('store_name_idx', table_name='purchase_reason_settings')
    op.drop_index(op.f('ix_purchase_reason_settings_store_id'), table_name='purchase_reason_settings')
    op.drop_table('purchase_reason_settings')
    op.drop_index(op.f('ix_portal_settings_store_id'), table_name='portal_settings')
    op.drop_index(op.f('ix_portal_settings_current_domain'), table_name='portal_settings')
    op.drop_table('portal_settings')
    op.drop_index(op.f('ix_plans_store_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_table('stores')
    # ### end Alembic commands ###
